### ISSUE TITLE
Dependency evaluation

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/fuzzy-encryption#2]
Once the target language for the implementation is identified, we need to figure out what existing packages we can rely on for underlying primitives, like the finite math components of the scheme. Do a review of existing packages to determine if they meet our bar and assemble a list of the ones we'll use, as well as the ones we'll need to develop ourselves.

**Comment by OR13** [comment]
yes, ideally we should start by pulling the mathmatical dependencies or any "standard" libraries into an inventory, such that we can evaluate language support for them.

**Comment by csuwildcat** [comment]
This is done in latest PR
