### ISSUE TITLE
Flint error installing on Windows 10 with WSL2

### ISSUE THREAD

**Issue by codeglobally** [decentralized-identity/fuzzy-encryption#5]
ERROR: Could not find a version that satisfies the requirement flint-py (from versions: none)
ERROR: No matching distribution found for flint-py

**Comment by KirkOlynyk** [comment]
$ pip3 install flint-py

This works on all our WSL distributions

**Comment by codeglobally** [comment]
Thank you for responding - on further digging it was a VS Code Remote-WSL issue.
